---
kind: pipeline
name: default

services:
  - name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go-admin-test

  - name: pgsql
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: go-admin-test

  - name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Aa123456

steps:
  - name: backend
    image: golang:1.14
    environment:
      GO111MODULE: on
      GOPROXY: off
    commands:
      - go version
      - echo "hello world"
      - apt-get update && apt-get install -y mysql-client
      - mysql -h mysql -u root -proot -e 'create database \`go-admin-test\`;'