---
kind: pipeline
name: mysql_test

clone:
  disable: true

services:
- name: db_mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: go-admin-test  

steps:  
- name: goadmin_test
  image: chg80333/goadmin-test:v3
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
  commands:
  - cd /go/src/github.com/GoAdminGroup/go-admin && git pull
  - git checkout -- go.mod go.sum
  - git checkout $DRONE_COMMIT
  - sleep 80
  - make mysql-test

---
kind: pipeline
name: postgresql_test

clone:
  disable: true

services:
- name: db_mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: go-admin-test  

steps:  
- name: goadmin_test
  image: chg80333/goadmin-test:v3
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
  commands:
  - cd /go/src/github.com/GoAdminGroup/go-admin && git pull
  - git checkout -- go.mod go.sum
  - git checkout $DRONE_COMMIT
  - sleep 80
  - make pg-test
  