kind: pipeline
name: default

clone:
  disable: true

steps:
# - name: clone
#   image: alpine/git
#   commands:
#   - git clone https://github.com/GoAdminGroup/go-admin.git .
#   - git checkout $DRONE_COMMIT

- name: goadmin_test
  image: chg80333/goadmin-test:v2
  environment:
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
  commands:
  - go get -u -v github.com/rakyll/gotest
  - go get -u -v github.com/gogf/gf@v1.12.1
  - sudo chmod -R 777 $GOPATH/pkg/mod/github.com/gogf/gf@v1.12.1/net/ghttp/ghttp_server_handler.go
  - sudo echo -e "\nfunc (s *Server) DefaultHttpHandle(w http.ResponseWriter, r *http.Request) { \n s.handleRequest(w, r) \n}\n" >> $GOPATH/pkg/mod/github.com/gogf/gf@v1.12.1/net/ghttp/ghttp_server_handler.go
  - cd /go/src/github.com/GoAdminGroup/go-admin && git pull
  - git checkout $DRONE_COMMIT
  - sleep 80
  - mysql -u root -proot -h db_mysql --execute="SELECT VERSION();"

services:
- name: db_mysql
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: go-admin-test