kind: pipeline
name: default

steps:
- name: test
  image: mysql:5.7
  commands:
  - sleep 200
  - mysql -u root -h db --execute="SELECT VERSION();"

services:
- name: db
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test