---
kind: pipeline
name: goadmin

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push
    - tag
    - pull_request

steps:
  - name: test
    pull: always
    image: golang:1.14
    environment:
      GO111MODULE: on
      GOPROXY: off
    commands:
      - go version