kind: pipeline
name: default

steps:
- name: goadmin_test
  image: chg80333/goadmin-test:v1
  commands:
  - sleep 500
  - mysql -u root -h database --execute="SELECT VERSION();"

services:
- name: database
  image: mysql:5.7
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: test